### ISSUE TITLE
[bug] Some application cannot detect itself and crashes 

### ISSUE THREAD

**Issue by boughtmy** [Dr-TSNG/Hide-My-Applist#1]
If the application itself is hidden in the template, the application will crash because it cannot detect itself. 

For example, Baidutieba, the error is as follows.

java.lang.UnsatisfiedLinkError: Expecting an absolute path of the library: /data/data/com.baidu.tieba/.jiagu/libjiagu.so
	at java.lang.Runtime.load0(Runtime.java:930)
	at java.lang.System.load(System.java:1631)
	at com.stub.StubApp.attachBaseContext(SourceFile:181)
	at android.app.Application.attach(Unknown Source:0)
	at android.app.Instrumentation.newApplication(Unknown Source:12)
	at android.app.LoadedApk.makeApplication(Unknown Source:60)
	at android.app.ActivityThread.handleBindApplication(Unknown Source:1205)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.MethodHooker.handleHookedMethod(MethodHooker.java:81)
	at EdHooker_42b8453bf7df105343083f1377c32094be493c49.hook(Unknown Source:48)
	at android.app.ActivityThread.access$1400(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:710)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loop(Unknown Source:249)
	at android.app.ActivityThread.main(Unknown Source:98)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:282)

**Comment by Dr-TSNG** [comment]
下个版本我会开发一个“不隐藏自己”的功能

**Comment by Dr-TSNG** [comment]
Updated "exclude self" function in 1.1, you can try if it works

**Comment by Dr-TSNG** [comment]
Solved
