### ISSUE TITLE
Maps scan & File detections cause app to crash

### ISSUE THREAD

**Issue by xx979xx** [Dr-TSNG/Hide-My-Applist#148]
Hi
I have this banking app "alrajhi bank" [apk link](https://drive.google.com/file/d/1y2tKjU_Stl3MLSa9WgC-WwKqMYi3lQ1x/view?usp=sharing), and it found a way to detect if Maps scan or File detections was activated in Hide-My-Applist and will crash immediately even when Magisk is uninstalled.

Phone model: Samsung Galaxy S8 (SM-G950F)
Android version: 9
ROM: stock G950FXXS9DTEA
Magisk version:  23.0
List of Magisk modules: HideMyApplist, Riru, Riru - LSPosed, Systemless Hosts, Busybox
LSPosed version: 1.7.2
List of LSPosed modules: Hide My Applist

```Process: com.alrajhiretailapp
PID: 3046
Flags: 0x38883e44
Package: com.alrajhiretailapp v7340174 (4.2.44)
Foreground: Yes
Build: samsung/dreamltexx/dreamlte:9/PPR1.180610.011/G950FXXS9DTEA:user/release-keys

java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.alrajhiretailapp-IKMRv4k-s9ifJJ4rugPlDA==/lib/arm64/libgjmfbagfmnem.so"
 at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
 at java.lang.System.loadLibrary(System.java:1669)
 at gvkkgci.au.d(Unknown Source:8)
 at gvkkgci.af.a(Unknown Source:13)
 at gvkkgci.af.a(Unknown Source:24)
 at gvkkgci.af.b(Unknown Source:6)
 at gvkkgci.af.<clinit>(Unknown Source:0)
 at gvkkgci.af.b(Unknown Source:0)
 at androidx.core.app.CoreComponentFactory.<clinit>(Unknown Source:0)
 at java.lang.Class.newInstance(Native Method)
 at android.app.LoadedApk.createAppFactory(LoadedApk.java:240)
 at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:768)
 at android.app.LoadedApk.getClassLoader(LoadedApk.java:847)
 at android.app.LoadedApk.getResources(LoadedApk.java:1088)
 at android.app.ContextImpl.createAppContext(ContextImpl.java:2563)
 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6100)
 at android.app.ActivityThread.access$1200(ActivityThread.java:237)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1785)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:214)
 at android.app.ActivityThread.main(ActivityThread.java:7050)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
 ```
 this is from an older version:

```
Process: com.alrajhiretailapp
PID: 17333
Flags: 0x38883e44
Package: com.alrajhiretailapp v3145859 (4.2.39)
Foreground: Yes
Build: samsung/dreamltexx/dreamlte:9/PPR1.180610.011/G950FXXS9DTEA:user/release-keys

java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.alrajhiretailapp-l6RTeqefS9QdpRplOgyUow==/lib/arm64/libgjmfbagfmnem.so"
 at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
 at java.lang.System.loadLibrary(System.java:1669)
 at rtkk.W.d(Unknown Source:8)
 at rtkk.ae.b(Unknown Source:13)
 at rtkk.ae.c(Unknown Source:24)
 at rtkk.ae.a(Unknown Source:6)
 at rtkk.ae.<clinit>(Unknown Source:0)
 at rtkk.ae.a(Unknown Source:0)
 at androidx.core.app.CoreComponentFactory.<clinit>(Unknown Source:0)
 at java.lang.Class.newInstance(Native Method)
 at android.app.LoadedApk.createAppFactory(LoadedApk.java:240)
 at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:768)
 at android.app.LoadedApk.getClassLoader(LoadedApk.java:847)
 at java.lang.reflect.Method.invoke(Native Method)
 at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:107)
 at LspHooker_.getClassLoader(Unknown Source:8)
 at android.app.LoadedApk.getResources(LoadedApk.java:1088)
 at android.app.ContextImpl.createAppContext(ContextImpl.java:2563)
 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6100)
 at java.lang.reflect.Method.invoke(Native Method)
 at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:107)
 at LspHooker_.handleBindApplication(Unknown Source:11)
 at android.app.ActivityThread.access$1200(ActivityThread.java:237)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1785)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:214)
 at android.app.ActivityThread.main(ActivityThread.java:7050)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
 ```
 Thank you for looking into this

**Comment by cracky5322** [comment]
@xx979xx After testing the application, it can be started without using HMA.

**Comment by xx979xx** [comment]
@cracky5322 That is True,
I am trying to used it with HMA, it will crash at launch. I thought there maybe an improvement to HMA to send the expected data to the app. it seems a missing information causing the app to crash

**Comment by cracky5322** [comment]
@xx979xx It is not recommended to enable additional features to block applications that do not need to be used, if you want to continue to try please read the announcement released in V2.3.2 Final Version, there is a reminder about the problem

**Comment by xx979xx** [comment]
Thanks

**Comment by xx979xx** [comment]
@cracky5322 I can confirm that HMA is working very well.
My issue is solved by upgrading to Magisk 24.
