### ISSUE TITLE
Crash when rotating screen

### ISSUE THREAD

**Issue by skrimix** [Dr-TSNG/Hide-My-Applist#19]
App crashes when I rotate screen on app list (both scope and template activities)

Crash log:
```
Process: com.tsng.hidemyapplist
PID: 2374
UID: 10548
Flags: 0xb0c8be44
Package: com.tsng.hidemyapplist v24 (1.5.3.2.Native)
Foreground: Yes
Process-Runtime: 16920557
Build: google/sunfish/sunfish:11/RQ2A.210505.002/7246365:user/release-keys
Crash-Tag: window_resize

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tsng.hidemyapplist/com.tsng.hidemyapplist.ui.ScopeManageActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.scwang.smart.refresh.layout.api.RefreshLayout com.scwang.smart.refresh.layout.SmartRefreshLayout.setOnRefreshListener(com.scwang.smart.refresh.layout.listener.OnRefreshListener)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5451)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5357)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.scwang.smart.refresh.layout.api.RefreshLayout com.scwang.smart.refresh.layout.SmartRefreshLayout.setOnRefreshListener(com.scwang.smart.refresh.layout.listener.OnRefreshListener)' on a null object reference
	at com.tsng.hidemyapplist.ui.ScopeManageActivity$SelectAppsFragment.onCreatePreferences(ScopeManageActivity.kt:84)
	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:160)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2684)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:280)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1175)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)
	at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2571)
	at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:236)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:315)
	at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:115)
	at com.tsng.hidemyapplist.ui.ScopeManageActivity.onCreate(ScopeManageActivity.kt:23)
	at android.app.Activity.performCreate(Activity.java:8000)
	at android.app.Activity.performCreate(Activity.java:7984)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
	... 13 more
```

**Comment by Dr-TSNG** [comment]
Fixed
