### ISSUE TITLE
[Bug] lsp激活后闪退

### ISSUE THREAD

**Issue by o0HalfLife0o** [Dr-TSNG/Hide-My-Applist#202]
### Steps to reproduce/复现步骤

安装hma后，在lsp未激活时，app一切正常，手机重启后，hma就再也打不开了

### Expected behaviour/预期行为

正常打开运行

### Actual behaviour/实际行为

lsp激活后重启手机，虽然隐藏应用列表有生效，但是hma的app再也打不开了

### Xposed Module List/Xposed 模块列表

```Shell
核心破解
noactive
r-安装组件
```

### Magisk Module List/Magisk 模块列表

```Shell
shamiko
gms doze
safetynet fix
zygisk-lsp
```

### Hide-My-Applist version/Hide-My-Applist 版本

v3.0.4-beta(361)

### Android version/Android 版本

12.1

### Magisk version/Magisk 版本

555a54ec-aplha

### Version requirement/版本要求

- [] I am using the latest [CI debug build](https://github.com/Dr-TSNG/Hide-My-Applist/actions) of Hide-My-Applist with detail log for debugging enabled/我正在使用最新 [CI 调试版本](https://github.com/Dr-TSNG/Hide-My-Applist/actions) 且启用详细日志

### Logs/日志
```
================================================================
    Generated by AppErrorsTracking
    Project Url: https://github.com/KitsunePie/AppErrorsTracking
================================================================
[Device Brand]: Xiaomi
[Device Model]: Redmi K20 Pro
[Display]: cherish_raphael-userdebug 12 SQ3A.220705.004 1660045467 release-keys
[Android Version]: 12
[API Version]: 32
[Package Name]: com.tsng.hidemyapplist
[Error Type]: Jvm
[Crash Time]: 2022年9月6日 13:47:08
[Stack Trace]:
java.lang.SecurityException: Unknown calling package name 'com.tsng.hidemyapplist'.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2426)
	at android.os.Parcel.createException(Parcel.java:2410)
	at android.os.Parcel.readException(Parcel.java:2393)
	at android.os.Parcel.readException(Parcel.java:2335)
	at h3.x.x(Unknown Source:33)
	at h3.e.m(SourceFile:2)
	at d2.f.c(Unknown Source:15)
	at h3.g0.c(Unknown Source:6)
	at h3.w.a(Unknown Source:6)
	at h3.c0.handleMessage(SourceFile:33)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at p3.lw0.dispatchMessage(Unknown Source:5)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7882)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by Dr-TSNG** [comment]
@o0HalfLife0o /data/system/hide_my_ applist*/config.json 发一下

**Comment by Dr-TSNG** [comment]
发 /data/system/hide_my_applist*/log/runtime.log

**Comment by keta1** [comment]
> @Dr-TSNG 
> [runtime.log](https://github.com/Dr-TSNG/Hide-My-Applist/files/9503012/runtime.log)
> 

[ INFO] 09-07 13:44:28 (PmsHookTarget30) @shouldFilterApplication caller: 10243 com.android.permissioncontroller, target: com.tsng.hidemyapplist


try not to hide com.tsng.hidemyapplist from com.android.permissioncontroller
