### ISSUE TITLE
[Bug] app crash

### ISSUE THREAD

**Issue by Charlie-Mars** [Dr-TSNG/Hide-My-Applist#207]
### Steps to reproduce/复现步骤

首次打开没有闪退，重启app后开始闪退，清应用数据重装后依然闪退

### Expected behaviour/预期行为

正常运行

### Actual behaviour/实际行为

启动闪退

### Xposed Module List/Xposed 模块列表

```Shell
核心破解
剪贴板过滤器
上帝模式
异常跟踪
hma
R安装组件
simple hook
tarnhelm
thanox
Xprivacylua
```

### Magisk Module List/Magisk 模块列表

```Shell
Shamiko
SafetyNet fix
Zygisk lsp
```

### Hide-My-Applist version/Hide-My-Applist 版本

V3.0.5-Beta.r367.8a56135-debug

### Android version/Android 版本

12.1

### Magisk version/Magisk 版本

Alpha 25203

### Version requirement/版本要求

Latest CI debug build/最新 CI debug 构建

### Logs/日志

Generated by AppErrorsTracking
Project Url: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: Xiaomi
[Device Model]: Mi MIX 2S
[Display]: SQ3A.220705.004
[Android Version]: 12
[API Version]: 32
[Package Name]: com.tsng.hidemyapplist
[Error Type]: Jvm
[Crash Time]: 2022年9月10日 下午8:21:40
[Stack Trace]:
java.lang.SecurityException: Unknown calling package name 'com.tsng.hidemyapplist'.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2426)
	at android.os.Parcel.createException(Parcel.java:2410)
	at android.os.Parcel.readException(Parcel.java:2393)
	at android.os.Parcel.readException(Parcel.java:2335)
	at com.google.android.gms.common.internal.zzac.getService(com.google.android.gms:play-services-basement@@18.0.0:9)
	at com.google.android.gms.common.internal.BaseGmsClient.getRemoteService(com.google.android.gms:play-services-basement@@18.0.0:14)
	at com.google.android.gms.common.internal.BaseGmsClient$LegacyClientCallbackAdapter.onReportServiceBinding(com.google.android.gms:play-services-basement@@18.0.0:2)
	at com.google.android.gms.common.internal.zzg.zzd(com.google.android.gms:play-services-basement@@18.0.0:1)
	at com.google.android.gms.common.internal.zza.zza(com.google.android.gms:play-services-basement@@18.0.0:4)
	at com.google.android.gms.common.internal.zzc.zze(com.google.android.gms:play-services-basement@@18.0.0:3)
	at com.google.android.gms.common.internal.zzb.handleMessage(com.google.android.gms:play-services-basement@@18.0.0:31)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by Charlie-Mars** [comment]
日志补充
[logcat_09-10-2022_20-27-16.txt](https://github.com/Dr-TSNG/Hide-My-Applist/files/9540336/logcat_09-10-2022_20-27-16.txt)

**Comment by ianchb** [comment]
@Charlie-Mars try not to hide com.google.android.gsf

**Comment by Charlie-Mars** [comment]
> @Charlie-Mars try not to hide com.tsng.hidemyapplist from com.google.android.gsf

![photo_2022-09-10_22-08-32](https://user-images.githubusercontent.com/74394539/189487108-ac4cb599-1d1e-42c9-99d5-42ea4ad79141.jpg)
still crash

**Comment by ianchb** [comment]
@Charlie-Mars Remove "com.google.android.gsf":{"useWhitelist":false,"excludeSystemApps":false,"applyTemplates":["TEMPLATENAME"],"extraAppList":[]}
in your config, and make it conform to json syntax.

**Comment by Charlie-Mars** [comment]
> @Charlie-Mars Remove "com.google.android.gsf":{"useWhitelist":false,"excludeSystemApps":false,"applyTemplates":["TEMPLATENAME"],"extraAppList":[]} in your config, and make it conform to json syntax.

it works,thanks
