### ISSUE TITLE
[BUG] 不知道为什么“系统服务未运行”

### ISSUE THREAD

**Issue by hahach** [Dr-TSNG/Hide-My-Applist#72]
装了2.0.9和2.0.5下面的riru模块，lsp里只选了推荐的系统框架，不管怎么重启都是 系统服务未运行，以为是app适配问题，换了几个旧版本也是如此

系统miui12.5，安卓10，不知道能提供什么log，这几个截图有用吗
![IMG_20210809_161118](https://user-images.githubusercontent.com/9148417/128677258-1a55ea0e-33ed-4a47-a21a-dce051f3405a.jpg)
![IMG_20210809_161133](https://user-images.githubusercontent.com/9148417/128677265-e3af8b00-581b-45cf-ba64-5e63dbc4fff0.jpg)
![Screenshot_2021-08-09-16-12-56-830_com tsng hidemyapplist](https://user-images.githubusercontent.com/9148417/128677276-52bea8e0-9924-4db2-9939-d0a98d958abd.jpg)

**Comment by Dr-TSNG** [comment]
@hahach 你lsp日志也不发鬼知道你什么问题

**Comment by hahach** [comment]
大佬，请！
为了减少阅读难度，这是直接重启后，点了一次你的app，看到还是服务未运行状态后提取的log
`LSPosed Log
--------- beginning of information
Manufacturer: Xiaomi
Brand: Xiaomi
Device: sagit
Product: 
Model: MI 6
Fingerprint: Xiaomi/sagit/sagit:7.1.1/NMF26X/V8.2.17.0.NCACNEC:user/release-keys
ROM description: sagit-user 7.1.1 NMF26X V8.2.17.0.NCACNEC release-keys
Architecture: arm64-v8a
Android build: 10
Android version: 10
Android sdk: 29
LSPosed version: v1.4.7 (5803)
Riru version: v26.0.5.r484.a8c93a12f8 (484)
Riru api: 26
Magisk: 23.0 (23000)
1970-02-13 04:02:07.007 E/android(1480-1480): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/server/pm/parsing/pkg/AndroidPackage;
	at java.lang.reflect.Executable.getParameterTypesInternal(Native Method)
	at java.lang.reflect.Method.getParameterTypes(Method.java:186)
	at java.lang.Class.getDeclaredMethods(Class.java:1884)
	at de.robv.android.xposed.XposedBridge.hookAllMethods(Unknown Source:5)
	at name.mikanoshi.customiuizer.utils.Helpers.hookAllMethods(Helpers.java:2)
	at name.mikanoshi.customiuizer.mods.PackagePermissions.hook(PackagePermissions.java:6)
	at name.mikanoshi.customiuizer.MainModule.handleLoadPackage(MainModule.java:3)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:28)
	at J0.beforeHookedMethod(:1)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:75)
	at LspHooker_.startBootstrapServices(Unknown Source:8)
	at com.android.server.SystemServer.run(Unknown Source:317)
	at com.android.server.SystemServer.main(Unknown Source:10)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:251)
Caused by: java.lang.ClassNotFoundException: com.android.server.pm.parsing.pkg.AndroidPackage
	... 18 more

1970-02-13 04:02:07.007 I/android(1480-1480): [HMA Xposed] [INFO] Config not cached, waiting for preference provider
1970-02-13 04:02:07.007 E/android(1480-1480): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/server/pm/parsing/pkg/AndroidPackage;
	at java.lang.reflect.Executable.getParameterTypesInternal(Native Method)
	at java.lang.reflect.Method.getParameterTypes(Method.java:186)
	at java.lang.Class.getDeclaredMethods(Class.java:1884)
	at com.tsng.hidemyapplist.xposed.XposedEntry.handleLoadPackage(SourceFile:78)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:28)
	at J0.beforeHookedMethod(:1)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:75)
	at LspHooker_.startBootstrapServices(Unknown Source:8)
	at com.android.server.SystemServer.run(Unknown Source:317)
	at com.android.server.SystemServer.main(Unknown Source:10)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:251)
Caused by: java.lang.ClassNotFoundException: com.android.server.pm.parsing.pkg.AndroidPackage
	... 15 more

1970-02-13 04:02:14.014 I/android(1480-1480): [HMA Xposed] [INFO] System hook installed (Version 59)`

**Comment by Aritro37** [comment]
@hahach 把你 ROM 的 service.jar post 上來

**Comment by hahach** [comment]
> @hahach 把你 ROM 的 service.jar post 上來

github 的 issue里没试过上传附件啊。。我onedrive分享吧
https://hahach-my.sharepoint.com/:u:/g/personal/emile_hahach_onmicrosoft_com/EVppn6Y216dBus-yghUEjVkB5rwKLa9--m4WcTAKGn9FKw?e=2E1ix8

**Comment by newNiu13** [comment]
应该是 lsposed 问题 一开始可以 后来不行就换回edxposed 又可以了

**Comment by keta1** [comment]
看起來不像模块的bug
试试更新下最新的lsposed,再测试下是否还有这个问题
