### ISSUE TITLE
Unneeded kotlin spam spamming in log.

### ISSUE THREAD

**Issue by eebssk1** [Dr-TSNG/Hide-My-Applist#8]
```
LSPosed Log
--------- beginning of information
Manufacturer: Xiaomi
Brand: Redmi
Device: phoenix
Product: Redmi K30
Model: Redmi K30
Fingerprint: POCO/phoenixin/phoenixin:10/QKQ1.190825.002/V12.0.2.0.QGHINXM:user/release-keys
ROM description: phoenixin-user 10 QKQ1.190825.002 V12.0.2.0.QGHINXM release-keys
Architecture: arm64-v8a
Android build: QQ3A.200805.001
Android version: 10
Android sdk: 29
LSPosed version: v1.3.5 (5557)
Riru version: v25.4.2.r415.f42e9c3 (415)
Riru api: 25
Magisk: 22.1 (22100)
2021-04-22 15:00:41.041 E/?(1584-1584): java.lang.NullPointerException: lpp.appInfo must not be null
	at com.tsng.hidemyapplist.xposed.hooks.IndividualHooks.handleLoadPackage(IndividualHooks.kt:13)
	at com.tsng.hidemyapplist.xposed.XposedEntry.handleLoadPackage(XposedEntry.kt:21)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:28)
	at X0.beforeHookedMethod(:1)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:75)
	at LspHooker_.startBootstrapServices(Unknown Source:8)
	at com.android.server.SystemServer.run(SystemServer.java:536)
	at com.android.server.SystemServer.main(SystemServer.java:365)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:918)

2021-04-22 15:00:44.044 I/?(1584-1584): [HMA LOG] [INFO] System hook installed
2021-04-22 15:00:44.044 I/?(1584-2600): [HMA LOG] [INFO] Waiting for preference provider
2021-04-22 15:03:33.033 E/?(1584-2602): java.lang.NullPointerException: null cannot be cast to non-null type kotlin.String
	at java.util.Objects.requireNonNull(Objects.java:228)
	at com.tsng.hidemyapplist.xposed.hooks.PackageManagerService$handleLoadPackage$1$setResult$1.beforeHookedMethod(PackageManagerService.kt:99)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:75)
	at LspHooker_.getPackageInfo(Unknown Source:25)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:1957)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4152)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)

2021-04-22 15:03:33.033 E/?(1584-3058): java.lang.NullPointerException: null cannot be cast to non-null type kotlin.String
	at java.util.Objects.requireNonNull(Objects.java:228)
	at com.tsng.hidemyapplist.xposed.hooks.PackageManagerService$handleLoadPackage$1$setResult$1.beforeHookedMethod(PackageManagerService.kt:99)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:75)
	at LspHooker_.getPackageInfo(Unknown Source:25)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:1957)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4152)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)

2021-04-22 15:13:23.023 E/?(1584-30600): java.lang.NullPointerException: null cannot be cast to non-null type kotlin.String
	at java.util.Objects.requireNonNull(Objects.java:228)
	at com.tsng.hidemyapplist.xposed.hooks.PackageManagerService$handleLoadPackage$1$setResult$1.beforeHookedMethod(PackageManagerService.kt:99)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:75)
	at LspHooker_.getPackageInfo(Unknown Source:25)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:1957)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4152)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)

2021-04-22 15:13:23.023 E/?(1584-30600): java.lang.NullPointerException: null cannot be cast to non-null type kotlin.String
	at java.util.Objects.requireNonNull(Objects.java:228)
	at com.tsng.hidemyapplist.xposed.hooks.PackageManagerService$handleLoadPackage$1$setResult$1.beforeHookedMethod(PackageManagerService.kt:99)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:75)
	at LspHooker_.getPackageInfo(Unknown Source:25)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:1957)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4152)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)

2021-04-22 15:14:08.008 E/?(1584-30473): java.lang.NullPointerException: null cannot be cast to non-null type kotlin.String
	at java.util.Objects.requireNonNull(Objects.java:228)
	at com.tsng.hidemyapplist.xposed.hooks.PackageManagerService$handleLoadPackage$1$setResult$1.beforeHookedMethod(PackageManagerService.kt:99)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:75)
	at LspHooker_.getPackageInfo(Unknown Source:25)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:1957)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4152)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)

2021-04-22 15:14:08.008 E/?(1584-7435): java.lang.NullPointerException: null cannot be cast to non-null type kotlin.String
	at java.util.Objects.requireNonNull(Objects.java:228)
	at com.tsng.hidemyapplist.xposed.hooks.PackageManagerService$handleLoadPackage$1$setResult$1.beforeHookedMethod(PackageManagerService.kt:99)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:75)
	at LspHooker_.getPackageInfo(Unknown Source:25)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:1957)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4152)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)

2021-04-22 15:23:55.055 E/?(1584-7597): java.lang.NullPointerException: null cannot be cast to non-null type kotlin.String
	at java.util.Objects.requireNonNull(Objects.java:228)
	at com.tsng.hidemyapplist.xposed.hooks.PackageManagerService$handleLoadPackage$1$setResult$1.beforeHookedMethod(PackageManagerService.kt:99)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:75)
	at LspHooker_.getPackageInfo(Unknown Source:25)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:1957)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4152)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)

2021-04-22 15:23:55.055 E/?(1584-7435): java.lang.NullPointerException: null cannot be cast to non-null type kotlin.String
	at java.util.Objects.requireNonNull(Objects.java:228)
	at com.tsng.hidemyapplist.xposed.hooks.PackageManagerService$handleLoadPackage$1$setResult$1.beforeHookedMethod(PackageManagerService.kt:99)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:75)
	at LspHooker_.getPackageInfo(Unknown Source:25)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:1957)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4152)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)

2021-04-22 15:23:55.055 E/?(1584-4323): java.lang.NullPointerException: null cannot be cast to non-null type kotlin.String
	at java.util.Objects.requireNonNull(Objects.java:228)
	at com.tsng.hidemyapplist.xposed.hooks.PackageManagerService$handleLoadPackage$1$setResult$1.beforeHookedMethod(PackageManagerService.kt:99)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:75)
	at LspHooker_.getPackageInfo(Unknown Source:25)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:1957)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4152)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)

2021-04-22 15:23:55.055 E/?(1584-7435): java.lang.NullPointerException: null cannot be cast to non-null type kotlin.String
	at java.util.Objects.requireNonNull(Objects.java:228)
	at com.tsng.hidemyapplist.xposed.hooks.PackageManagerService$handleLoadPackage$1$setResult$1.beforeHookedMethod(PackageManagerService.kt:99)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:75)
	at LspHooker_.getInstallerPackageName(Unknown Source:11)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:3057)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4152)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)

2021-04-22 15:23:55.055 E/?(1584-7435): java.lang.NullPointerException: null cannot be cast to non-null type kotlin.String
	at java.util.Objects.requireNonNull(Objects.java:228)
	at com.tsng.hidemyapplist.xposed.hooks.PackageManagerService$handleLoadPackage$1$setResult$1.beforeHookedMethod(PackageManagerService.kt:99)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:75)
	at LspHooker_.getPackageInfo(Unknown Source:25)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:1957)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4152)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)

2021-04-22 15:23:55.055 E/?(1584-7435): java.lang.NullPointerException: null cannot be cast to non-null type kotlin.String
	at java.util.Objects.requireNonNull(Objects.java:228)
	at com.tsng.hidemyapplist.xposed.hooks.PackageManagerService$handleLoadPackage$1$setResult$1.beforeHookedMethod(PackageManagerService.kt:99)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:75)
	at LspHooker_.getPackageInfo(Unknown Source:25)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:1957)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4152)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)

```
Developers should handle these cases on their own instead of let kotlin clean their ass. These should be dropped if not useful to let the module looks less "bug".

Thanks.

**Comment by Dr-TSNG** [comment]
I'll fix these "benign bugs" after solving the "big bugs" like issue #4

**Comment by Dr-TSNG** [comment]
Should have fixed this in the latest version, please check if it works.

**Comment by eebssk1** [comment]
Tested, no such problem anymore. Feel free to close this issue 嘿嘿.

**Comment by Dr-TSNG** [comment]
Solved
